version: "3.2"

services:
  #MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./mariadb.env
    restart: always

  #GLPI Container
  glpi:
    image: triatk/glpi-standalone:11.0.0
    container_name: glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/www/html/glpi/:/var/www/html/glpi
    environment:
      - TIMEZONE=Europe/Brussels
      #- GLPI_ALIAS=glpi  # Optional, uncomment to deploy GLPI in a subfolder, default subdir is /glpi
      - VERSION_GLPI=11.0.0 # Optional, default to 10.0.18
      - VERSION_PHP=8.3 # Optional, default to 8.3
      - INSTALL_PLUGINS=false # Optional, default to false
      - OPCACHE_SIZE=128 # Optional, default to 128
      - OPCACHE_BUFFER=8 # Optional, default to 8
      - OPCACHE_WASTED_PERCENTAGE=5 # Optional, default to 5
    restart: always
